### ISSUE TITLE
Fails on 204 (No Content) response

### ISSUE THREAD

**Issue by bertdeblock** [ef4/ember-resource-metadata#14]
First of all, thanks for the addon, saved me a bunch of work 👌

It appears the addon always assumes that the response contains an object: https://github.com/ef4/ember-resource-metadata/blob/master/addon/adapter-mixin.js#L9

However in some cases the API might return a 204 (No Content) response (https://jsonapi.org/format/#crud-updating-relationship-responses-204), in which case the response is empty and destructuring will fail.

**Comment by enterpub** [comment]
Hi, guys. I have exactly the same issue. I'm making a PATCH request, which returns empty response -> error happens. 
Error: Cannot destructure property `data` of 'undefined' or 'null'

**Comment by ef4** [comment]
Thanks for reporting and thanks for @bertdeblock for the PR that fixes this. I haven't been able to prioritize figuring out what's wrong with CI over there. If somebody else can, we can get this merged and released.

**Comment by enterpub** [comment]
Hi, any update about fixing this issue? @ef4 Is it possible, that CI works now?
