### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by serinyoon** [ef4/ember-resource-metadata#5]
Hi. 
I wanted to use the addon for my ember project but I get an error when I do `npm install/search ember-resource-metadata`:

```bash
npm ERR! code E404
npm ERR! 404 Not Found: ember-resource-metadata@latest
```

Is this addon still available for use?

**Comment by ef4** [comment]
Yes, nothing was unpublished. Maybe you hit a temporary problem with npm's hosting.
